### ISSUE TITLE
Use Firebase to host package.elm-lang.org (static assets and package metadata)

### ISSUE THREAD

**Issue by vilterp** [elm-lang/elm-plans#15]
Wrote as a Google Doc because I'm lazy; comments here are best

https://docs.google.com/document/d/1s0kO4K53I6kacbPOz1qxjWRBN3SgguSKvsC-Fw3bp0o/edit?usp=sharing

**Comment by vilterp** [comment]
Cost is not good: Firebase $45/month vs. DigitalOcean VPS $5 month.

**Comment by Apanatshka** [comment]
Perhaps there is a Firebase alternative you can run on DigitalOcean yourself? Or would that negate most of the upsides?

**Comment by vilterp** [comment]
It probably would. After talking with Evan, it seems that for now, adding endpoints for download stats to the current Haskell server is probably the cheapest in terms of developer time & monetary cost.

Really wish firebase were cheaper, because it looks like it would make adding features to the package site really easy.

**Comment by scottcorgan** [comment]
http://divshot.com
