### ISSUE TITLE
Discussion: How to handle user-defined types that want to go through main?

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-plans#19]
The issue here has prompted me to think a bit about this. https://groups.google.com/forum/#!topic/elm-discuss/9fxTs7hVDaI

My goal here is to start a discussion that would result in an actual proposal that could then be considered to be added to Elm.
## Problem

`main` currently accepts the `Html` type which is dependent on the `virtual-dom` library. While this is fine for a number of applications, it would be nice to be able to support different interfaces (in this case, the interface requested is `incremental-dom`). One may also imagine a `React` interface or other.

Furthermore, as Elm is contemplating different compilation targets (like node), the importance for more types to go through main will increase.
## Current Solutions/Workarounds
1. Lie to the compiler and hope for the best
2. Hack the compiler/include extra scripts to get your type through main
3. Bug @evancz until he whitelists your type in the compiler
## Considered Solution

Add a qualifier before the `type` keyword like `executable` or `runnable` or `renderable` and have any type preceded by this qualifier go through main.

``` elm
runnable type ReactComponent = ...

runnable type IncrementalDomComponent = ...
```
## Why is this not a proposal?

I think my solution is weird and not very good. It is important to note that this is supposed to be an ultra-expert feature to be used in rare conditions. Verily, there will be very few types that will ever want to go through main directly. 

So, my question is: **Is it good enough if packages just make a formal request to have their special type go through main or should there be some mechanism to allow package authors to do this themselves?**
## Further considerations

I would also like to point out that the solution to allowing different html interfaces/v-dom implementations in Elm could come from a different angle, perhaps a suitable abstraction could do the trick. I would like the discussion to also consider this angle as it could conceivably solve this issue differently.

**Comment by evancz** [comment]
I am in the process of closing down this repo. This idea makes sense. I have it on my own personal list, so I'll bring you into the discussion when I have time to work on this.

**Comment by evancz** [comment]
If you want to preserve this, move it to a gist. I will probably delete this repo in a couple days and salvage certain pieces for managing other repos.

**Comment by evancz** [comment]
This is also related to https://github.com/elm-lang/core/issues/324 which is in the "for consideration" mega thread on core.
