### ISSUE TITLE
Some syntax changes

### ISSUE THREAD

**Issue by gyzerok** [elm-lang/elm-plans#22]
I'm a JavaScript developer curious about trying Elm. For now there are only two things that prevents me from doing that.
1. JSX (html) is a way for declaring html which people are famaliar with. Not only programmers, but designers and some other ones. As I've understood Facebook created JSX to solve the issue with familiarity and not to force people use terrible way of `React.createElement`. So I highly request adding support for JSX into Elm.
2. Elm is trying to simplify some syntax like not using parentheses for functions but on the other hand adds some ugly constructions (from JS developer point of view)

Isn't this

``` elm
type alias Circle =
    x : Float
    y : Float
    radius : Float
```

much nicer than this?

``` elm
type alias Circle =
    { x : Float
    , y : Float
    , radius : Float
    }
```

Or you can add trailing commas to free people from using this terrible commas at the start of the line. With trailing commas we would have similar diff behaviour with much cleaner syntax.

What do you think about this guys?

**Comment by gyzerok** [comment]
Or if JSX is not possible I propose way to rely more on indentation
Isn't this

``` elm
view address model =
  div []
    button [ onClick address Decrement ] [ text "-" ]
    div [] [ text (toString model) ]
    button [ onClick address Increment ] [ text "+" ]
```

much cleaner than this?

``` elm
view address model =
  div []
    [ button [ onClick address Decrement ] [ text "-" ]
    , div [] [ text (toString model) ]
    , button [ onClick address Increment ] [ text "+" ]
    ]
```

Its similar to Jade way

**Comment by jvoigtlaender** [comment]
As far as I know, trailing commas are coming in the next release 0.16 of Elm, but the completely replacing commas by indentation you suggest has been suggested before, discussed at length, and discarded. Probably you can find that discussion linked in some recently closed issue around here.

**Comment by jvoigtlaender** [comment]
Put differently, one half of your suggestions is a duplicate. The other half, JSX-likeness, may not have been discussed at length yet. Maybe take it for discussion to the mailing list?

**Comment by gyzerok** [comment]
@jvoigtlaender Oh, I see now. Trailing commas to the rescue!

So the last thing which feels ugly for me in Elm is a way of declaring html. With trailing commas it would be much nicer:

``` elm
view address model =
  div [] [
    button [ onClick address Decrement ] [ text "-" ],
    div [] [ text (toString model) ],
    button [ onClick address Increment ] [ text "+" ],
  ]
```

Am I right with this syntax after 0.16?

**Comment by jvoigtlaender** [comment]
Yes, I believe this is going to be legal syntax in Elm 0.16. But see https://github.com/elm-lang/elm-plans/issues/2#issuecomment-134439053. I don't know whether that is the latest word on this question.

**Comment by gyzerok** [comment]
I would try to put JSX proposal in much cleaner way tomorrow and would
close this issue. Thank you guys.
25.09.2015 1:52 пользователь "Janis Voigtländer" notifications@github.com
написал:
