### ISSUE TITLE
Any thoughts on compiling Elm to native mobile code for android and iOS?

### ISSUE THREAD

**Issue by AWaselnuk** [elm-lang/elm-plans#23]
Are there any thoughts around doing something along the lines of react native at any point in the future? My guess is it has probably crossed your mind but would be way in the future.

**Comment by evancz** [comment]
Yeah, this is something I have thought about a lot. I'll be working on it in time, but not for now.

We don't really use elm-plans for this kind of thing anymore. Folks on elm-discuss should know about the history of folks looking into this and can help out there :)
