### ISSUE TITLE
Allow trailing commas

### ISSUE THREAD

**Issue by dasch** [elm-lang/elm-plans#24]
I gotta say, I found the Elm coding style really weird at first. You definitely can get used to it, but it's still a source of frustration for me.

I totally understand the reason for the style though, and agree that "diff-ability" (?) and isolated changesets are very important real-world goals.

However, I think there's a simpler way to achieve that: allow trailing commas. This works well in Ruby:

``` ruby
things = [
  "one",
  "two",
  "three",
]
```

It could work equally well in Elm:

``` elm
thing = {
  one = "one",
  two = "two",
  three = "three",
}

vs.

thing =
  { one = "one"
  , two = "two"
  , three = "three"
  }
```

I realize it may be a bit late to change the style, though.

**Comment by jvoigtlaender** [comment]
As far as I know, trailing commas are already slated to appear in the next release of Elm. :smile:

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-plans/issues/2 (and close this issue, I guess).

**Comment by dasch** [comment]
Ah. Is there a place to get an overview of planned syntax changes? It seems like all the issues I find are closed, pointing to the repo, but there are no corresponding issues here.

**Comment by jvoigtlaender** [comment]
> Ah. Is there a place to get an overview of planned syntax changes?

No, I don't think so. The archive of the mailing list may be the best place to look.

> It seems like all the issues I find are closed, pointing to the repo, but there are no corresponding issues here.

For one thing, as Evan explains at the end of #2 (and in other issues), he is not planning to use https://github.com/elm-lang/elm-plans/ for planning anymore.

Moreover, closing issues in this and others of Evan's repos does not necessarily mean that the issues are resolved. (In other words, when searching for issues on a topic, you may have to look at closed ones as well.) See https://github.com/evancz/start-app/issues/35#issuecomment-148939344 for a description of this fact (or problem?) by @rgrempel.

**Comment by dasch** [comment]
Yeah, all of those points mean it's harder for a newcomer to figure out what is and isn't planned, how to engage with the community in a good way, etc :-/
