### ISSUE TITLE
Elm automatic source code formatter

### ISSUE THREAD

**Issue by tiziano88** [elm-lang/elm-plans#28]
Is there any interest in building a source code formatter (a la [gofmt](https://golang.org/cmd/gofmt/) or [rustfmt](https://github.com/rust-lang-nursery/rustfmt)) enforcing Elm best practices? Given the AST representation of a file, it should not be too hard to basically pipe that into a pretty format function to generate its "canonical" representation.

**Comment by jvoigtlaender** [comment]
https://github.com/avh4/elm-format :smile:

**Comment by tiziano88** [comment]
Oh well, I'm obviously late to the party :stuck_out_tongue: apologies, closing
