### ISSUE TITLE
Proposal: Local imports

### ISSUE THREAD

**Issue by keleshev** [elm-lang/elm-plans#5]
Like Elm, OCaml does not allow overloading functions and operators. However, it is desirable to use the same function names and operators in different context. For example, you might want to use operators `+`, `*`, `^` and so on for vector math. 

Right now you are forced to define more obscure operators such as for example `+.`, `-.`, `^.` for vector math.

OCaml solves this with "local import", which they call ["local open"](https://realworldocaml.org/v1/en/html/files-modules-and-programs.html#opening-modules). It allows to import contents of a module in a limited scope. The syntax for it is `<module name>.(<expression>)`, for example:

``` ocaml
Vector.(v + 2.0 * w)
```

Here, inside the parenthesis operators `+` and `*` operate on vectors (`*` multiplies a vector by a factor). Outside the parenthesis these operators stand for regular math.

Here's an example on how this could look in Elm:

``` elm
-- vector.elm
module Vector where

type alias Vector = { x: Float, y: Float }

(*) : Float -> Vector -> Vector
(*) factor vector =
  { vector | x <- Float.(vector.x * factor)
           , y <- Float.(vector.y * factor) }

(+) : Vector -> Vector -> Vector
(+) v w = 
  { v | x <- Float.(v.x + w.x)
      , y <- Float.(v.y + w.y) }

-- test.elm
v = { x=5, y=5 }
w = { x=0, y=2 }

Vector.(v + 2 * w) == { x=0, y=20 }
```

In this example we also use local import to access `Float` operators in order to distinguish them from `Vector` operators inside `vector.elm`.

**Comment by texastoland** [comment]
Something like this could also be interesting for exposing instance arguments if rank-2 poly is in the future.

**Comment by rtfeldman** [comment]
It's not as concise, but for what it's worth you can already do this with `let` shadowing:

``` elm
let
    (+) = Vector.plus
    (*) = Vector.times 
in
    v + 2 * w
```

That said, I'd personally rather this use case be solved by something typeclassy down the line than by something like open imports.

**Comment by Apanatshka** [comment]
As a PL person, I'm thinking "omg, this is cool". 
But I think I'm with @rtfeldman that this would be something a future typeclassy system could solve, and probably in a more powerful way. Though I do really like how the use of the module name close to the operators clarifies which exact operators you're using.

**Comment by keleshev** [comment]
Type classes vs. ML modules is an open question. You might find [this paper and discussion interesting](http://lambda-the-ultimate.org/node/1558).

At the same time local imports only help you control the scope of your imports, nothing sophisticated like type classes or ML modules. In my experience it is useful to limit the import scope to minimum. In the end this has very little to do with type classes vs. ML modules. Local imports could be useful with both.

**Comment by texastoland** [comment]
@keleshev Thanks for the reference I added a couple critiques to Instapaper :pray:

**Comment by evancz** [comment]
I don't know the answer right now, and I am closing down this repo. Right now I don't think there is a compelling enough use case, but we can revisit this at a later time. I will not forget about this, so consider it stored away.

**Comment by keleshev** [comment]
For historical purpose, I'll mention another use-case that I had in mind for local imports: convenient scoping of DSL-like modules. With local imports you can do the following:

``` elm
import Html

main =
  Html.(ul [class "grocery-list"] [li [] [text "Pamplemousse"], li [] [text "Ananas"]])
```

instead of the usual:

``` elm
import Html exposing (li, text, ul, class)

main =
  ul [class "grocery-list"] [li [] [text "Pamplemousse"], li [] [text "Ananas"]]
```

So if you have a DSL with many functions it allows to import them only locally instead of polluting current module namespace. This is especially useful for cases when you have short or obscure names like `li`, `ul`, which are easy to shadow. 

Another example could be JSON handling. You could write the following:

``` elm
import Json.Encode

person =
    Json.Encode.(object [ ("name", string "Tom"), ("age", int 42) ])
```

instead of:

``` elm
import Json.Encode exposing (object, string, int)

person =
    object [ ("name", string "Tom"), ("age", int 42) ]
```

I think JSON example is even more compelling, because the module defines such common symbols as "object", "string" and "int".

**Comment by evancz** [comment]
That is a pretty compelling example, thanks for sharing that!

It feels like this could help with https://github.com/elm-lang/elm-compiler/issues/908, but I'm not sure how yet. Anyway, thanks again!

**Comment by rtfeldman** [comment]
Seems intuitive to [allow `import` inside `let`](https://gist.github.com/rtfeldman/be1ca931a1d81b34cf3a), which I'll stash in a gist since this repo is on its way out. :smile:

**Comment by keleshev** [comment]
@rtfeldman actually OCaml hast a similar form too: `let open Module in expression` (`exposing (..)` is implicit, though), however in my experience it is used less often than `Module.(expression)` form. For comparison:

``` elm
import Json.Encode

person =
    Json.Encode.(object [ ("name", string "Tom"), ("age", int 42) ])
```

``` elm
import Json.Encode

person =
    let import Json.Encode exposing (..) in
    object [ ("name", string "Tom"), ("age", int 42) ]
```

**Comment by keleshev** [comment]
Just remembered that I wrote a blog post a while ago that lists all the ways you can import things in OCaml, so here's the link in case you want some inspiration:
- http://keleshev.com/namespacing-variants-in-ml
