### ISSUE TITLE
takeLast for Arrays and Strings

### ISSUE THREAD

**Issue by ryepesg** [elm-lang/elm-plans#8]
Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

**Comment by dnalot** [comment]
I believe Haskell has `init` and `last` as corrolary

**Comment by texastoland** [comment]
Makes sense to me. What's your specific use case? Has it come up often?

**Comment by mgold** [comment]
What about changing `Array.get` to accept a negative index? And what's wrong with `String.right 1`?

**Comment by ryepesg** [comment]
Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])Getting the last elements form an Array or String involves getting first the length. Array.slice already support negative index, but it extracts up to but not including end.

Python:

```
>>> [1, 2, 3, 4, 5][-2:]
[4, 5]
>>> [1, 2, 3, 4, 5][-1:]
[5]
>>> [1, 2, 3, 4, 5][-1]
5
>>> '"xyzelm"[-3:]
elm

```

Clojure:

```
user=> (take-last 2 [1 2 3 4 5])
(4 5)
user=> (take-last 1 [1 2 3 4 5])
(5)
user=> (last [1 2 3 4 5])
5
user=> (subs "xyzelm" 3)
"elm"

```

The equivalent behaviour in Elm would be:

```
> Array.takeLast 2 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [4, 5])

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

> Array.takeLast 1 <| Array.fromList [1, 2, 3, 4, 5]
(Array.fromList [5])

> String.takeLast 3 <| "xyzelm"
"elm"

```

**Comment by ryepesg** [comment]
@dnalot: When porting my Python/Clojure(Script) code to Haskell/Elm, I've noted the one single place where my code is less expressive is while doing string and array manipulation (my application reads source code and does log analysis), and the "take last" thing is the most evident difference.

@mgold: I was not aware of `String.right`. Since `List.drop` is symmetric with `String.drop[Right]`, I was expecting `List.take` were symmetric with `String.take[Right]`. `String.right` doesn't make sense to me because `right` is an adjective instead of a verb. About `Array.get` with negative index, I agree it would be a nice addition, but it is complementary since it doesn't cover all use cases of Array.takeRight. Let me explain the ideal world of coherence among List, String and Array in eight steps.

I think for symmetry with List.take and List.drop we could:
1) Rename `String.left` to `String.take`.
2) Rename `String.right` to `String.takeRight`.
3) Rename `String.dropLeft` to `String.drop`.
String is complete because covers all the possibilities of Python (when left index is missing it assumes starting from 0, when right index is missing it assumes ending in length of array):

```
[:x] -> String.take       
[-x:] -> String.takeRight  
[x:] -> String.drop      
[:-x] -> String.dropRight  
[x:y] -> String.slice      
```

However, `take` and `dropRight` are easily emulated with `slice 0`, so we could then:
4) Remove `String.take`.
5) Remove `String.dropRight`.

Array.slice covers easily combinations starting in any index, including 0:

```
[:x] -> Array.slice 0 x 
[:-x] -> Array.slice 0 -x 
[x:y] -> Array.slice x y
[x:-y] -> Array.slice x -y
```

However in the last two lines, nowadays we can't express `y` being exactly the end, so then we could:
7) Add Array.drop
8) Add Array.takeRight

**Comment by evancz** [comment]
I'm closing down this repo, so can you open an issue on core for "Add `Array.left` and `Array.right`" that'd match how it works on strings? I'll add it to the "for consideration" thread after that.
